minio:
  # bucket名称
  bucket: ethons
  # Minio服务地址
  host: http://192.168.0.115:9000
  # 访问路径
  url: "${minio.host}/${minio.bucket}/"
  # MINIO_ACCESS_KEY
  accessKey: ethons
  # MINIO_SECRET_KEY
  secretKey: 12345689
file:
  store-path: D:\docker\nginx\www\bbb
  http-path: http://localhost:8888/bbb
